[package]
name = "mcp-types"
version = "0.1.0"
edition = "2021"
authors = ["Rakibul Yeasin <ryeasin03@gmail.com>"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
rmcp = { workspace = true }
async-trait = { workspace = true }
