[package]
name = "mcp-types"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Use official rmcp SDK for MCP types
rmcp.workspace = true
serde.workspace = true
serde_json.workspace = true
