[package]
name = "mcp-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
async-trait.workspace = true
uuid.workspace = true
reqwest.workspace = true
futures.workspace = true
url.workspace = true
eventsource-stream = "0.2"

mcp-types = { path = "../mcp-types" }

[features]
default = ["http", "sse"]
http = []
sse = []
